/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package defeito;

import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class jCadastroDef extends javax.swing.JInternalFrame {

    /**
     * Creates new form jCadastroDef
     */
    public jCadastroDef() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_defeito = new javax.swing.JPanel();
        label_defeito = new javax.swing.JLabel();
        texta_defeito = new javax.swing.JTextField();
        label_solucao = new javax.swing.JLabel();
        texta_solucao = new javax.swing.JTextField();
        label_info = new javax.swing.JLabel();
        button_defeito = new javax.swing.JButton();
        box_subsoft = new javax.swing.JCheckBox();
        box_subhard = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(102, 102, 102));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Defeitos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_icones/computer_error.png"))); // NOI18N

        panel_defeito.setBackground(new java.awt.Color(102, 102, 102));

        label_defeito.setBackground(new java.awt.Color(102, 102, 102));
        label_defeito.setForeground(new java.awt.Color(0, 0, 0));
        label_defeito.setText("Defeito informado:");

        texta_defeito.setEditable(false);
        texta_defeito.setBackground(new java.awt.Color(255, 255, 255));
        texta_defeito.setForeground(new java.awt.Color(0, 0, 0));

        label_solucao.setBackground(new java.awt.Color(102, 102, 102));
        label_solucao.setForeground(new java.awt.Color(0, 0, 0));
        label_solucao.setText("Qual técnica foi usada para verificar o erro:");

        texta_solucao.setBackground(new java.awt.Color(255, 255, 255));
        texta_solucao.setForeground(new java.awt.Color(0, 0, 0));

        label_info.setBackground(new java.awt.Color(255, 255, 255));
        label_info.setForeground(new java.awt.Color(0, 0, 0));
        label_info.setText("(marque as caixas para \"Sim\")");

        button_defeito.setText("Salvar e Proximo");

        box_subsoft.setBackground(new java.awt.Color(102, 102, 102));
        box_subsoft.setForeground(new java.awt.Color(0, 0, 0));
        box_subsoft.setText("Foi necessário substituir algum Software?");

        box_subhard.setBackground(new java.awt.Color(102, 102, 102));
        box_subhard.setForeground(new java.awt.Color(0, 0, 0));
        box_subhard.setText("Foi necessário substituir algum Hardware?");

        javax.swing.GroupLayout panel_defeitoLayout = new javax.swing.GroupLayout(panel_defeito);
        panel_defeito.setLayout(panel_defeitoLayout);
        panel_defeitoLayout.setHorizontalGroup(
            panel_defeitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_defeitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_defeitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_defeitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panel_defeitoLayout.createSequentialGroup()
                            .addGroup(panel_defeitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(box_subhard)
                                .addGroup(panel_defeitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(label_solucao)
                                    .addComponent(texta_defeito, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                                    .addComponent(texta_solucao))
                                .addComponent(label_defeito))
                            .addGap(78, 78, 78))
                        .addGroup(panel_defeitoLayout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(label_info)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_defeito)
                            .addContainerGap()))
                    .addComponent(box_subsoft)))
        );
        panel_defeitoLayout.setVerticalGroup(
            panel_defeitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_defeitoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_defeito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texta_defeito, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_solucao)
                .addGap(18, 18, 18)
                .addComponent(texta_solucao, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(box_subsoft)
                .addGap(8, 8, 8)
                .addComponent(box_subhard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_defeitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_defeito)
                    .addComponent(label_info))
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_defeito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_defeito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox box_subhard;
    private javax.swing.JCheckBox box_subsoft;
    private javax.swing.JButton button_defeito;
    private javax.swing.JLabel label_defeito;
    private javax.swing.JLabel label_info;
    private javax.swing.JLabel label_solucao;
    private javax.swing.JPanel panel_defeito;
    private javax.swing.JTextField texta_defeito;
    private javax.swing.JTextField texta_solucao;
    // End of variables declaration//GEN-END:variables
}
