/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package defeito;

import maquinas.JCadastro;
import clientes.JClientePerg;
import conexao.conexao_bd;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class jCadastroDef extends javax.swing.JInternalFrame {
    JCadastro jc = new JCadastro();
    JClientePerg jcp = new JClientePerg();
    conexao_bd cbd = new conexao_bd();
   
    /**
     * Creates new form jCadastroDef
     */
    public jCadastroDef() {
        initComponents();
    }
    
    public void reseta(){
        texta_defeito.setText("");
        texta_solucao.setText("");
        text_orcamento.setText("0");
    }
    
    public void defeitoInfo(String defeito){
        texta_defeito.setText(defeito);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_defeito = new javax.swing.JPanel();
        label_defeito = new javax.swing.JLabel();
        label_solucao = new javax.swing.JLabel();
        button_defeito = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        texta_solucao = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        texta_defeito = new javax.swing.JTextArea();
        label_orcprevisto = new javax.swing.JLabel();
        text_orcamento = new javax.swing.JTextField();
        box_status = new javax.swing.JComboBox<>();
        label_orcstatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Defeitos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_icones/computer_error.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(345, 445));
        setPreferredSize(new java.awt.Dimension(345, 445));

        panel_defeito.setBackground(new java.awt.Color(51, 51, 51));

        label_defeito.setBackground(new java.awt.Color(51, 51, 51));
        label_defeito.setForeground(new java.awt.Color(255, 255, 255));
        label_defeito.setText("Defeito informado:");

        label_solucao.setBackground(new java.awt.Color(51, 51, 51));
        label_solucao.setForeground(new java.awt.Color(255, 255, 255));
        label_solucao.setText("Solução:");

        button_defeito.setBackground(new java.awt.Color(255, 255, 255));
        button_defeito.setForeground(new java.awt.Color(0, 0, 0));
        button_defeito.setText("Proximo");
        button_defeito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_defeitoMouseClicked(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        texta_solucao.setBackground(new java.awt.Color(255, 255, 255));
        texta_solucao.setColumns(20);
        texta_solucao.setForeground(new java.awt.Color(0, 0, 0));
        texta_solucao.setRows(5);
        jScrollPane1.setViewportView(texta_solucao);

        jScrollPane3.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));

        texta_defeito.setEditable(false);
        texta_defeito.setBackground(new java.awt.Color(255, 255, 255));
        texta_defeito.setColumns(20);
        texta_defeito.setForeground(new java.awt.Color(0, 0, 0));
        texta_defeito.setRows(5);
        jScrollPane3.setViewportView(texta_defeito);

        label_orcprevisto.setBackground(new java.awt.Color(51, 51, 51));
        label_orcprevisto.setForeground(new java.awt.Color(255, 255, 255));
        label_orcprevisto.setText("Orçamento Previsto:");

        text_orcamento.setBackground(new java.awt.Color(255, 255, 255));
        text_orcamento.setForeground(new java.awt.Color(0, 0, 0));
        text_orcamento.setText("0");

        box_status.setBackground(new java.awt.Color(255, 255, 255));
        box_status.setForeground(new java.awt.Color(0, 0, 0));
        box_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));

        label_orcstatus.setBackground(new java.awt.Color(51, 51, 51));
        label_orcstatus.setForeground(new java.awt.Color(255, 255, 255));
        label_orcstatus.setText("Orçamento Aprovado:");

        javax.swing.GroupLayout panel_defeitoLayout = new javax.swing.GroupLayout(panel_defeito);
        panel_defeito.setLayout(panel_defeitoLayout);
        panel_defeitoLayout.setHorizontalGroup(
            panel_defeitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_defeitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_defeitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_defeitoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button_defeito))
                    .addGroup(panel_defeitoLayout.createSequentialGroup()
                        .addGroup(panel_defeitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_solucao)
                            .addComponent(label_defeito)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_defeitoLayout.createSequentialGroup()
                                .addComponent(label_orcprevisto)
                                .addGap(18, 18, 18)
                                .addComponent(text_orcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_defeitoLayout.createSequentialGroup()
                                .addComponent(label_orcstatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(box_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_defeitoLayout.setVerticalGroup(
            panel_defeitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_defeitoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_defeito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(label_solucao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(panel_defeitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_orcprevisto)
                    .addComponent(text_orcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_defeitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_orcstatus)
                    .addComponent(box_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(button_defeito)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_defeito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_defeito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(800, 400, 313, 445);
    }// </editor-fold>//GEN-END:initComponents

    private void button_defeitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_defeitoMouseClicked
        if(texta_solucao.getText().equals("")){
            cbd.Defeito(texta_defeito.getText());
        }else{
            cbd.DefeitoSolucao(texta_defeito.getText(), texta_solucao.getText());
        }
        JOptionPane.showMessageDialog(null, "Informações Salvas Com Sucesso!");
        JDesktopPane desktop = getDesktopPane();
        desktop.add(jcp);
        jcp.setVisible(true);
        this.dispose();
        reseta();

    }//GEN-LAST:event_button_defeitoMouseClicked
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_status;
    private javax.swing.JButton button_defeito;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_defeito;
    private javax.swing.JLabel label_orcprevisto;
    private javax.swing.JLabel label_orcstatus;
    private javax.swing.JLabel label_solucao;
    private javax.swing.JPanel panel_defeito;
    private javax.swing.JTextField text_orcamento;
    private javax.swing.JTextArea texta_defeito;
    private javax.swing.JTextArea texta_solucao;
    // End of variables declaration//GEN-END:variables
}
