/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package conexao;

import conexao.conexao_bd;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author Aluno
 */
public class JClienteExistente extends javax.swing.JInternalFrame {
    
    static String url ="jdbc:mysql://172.20.126.128:3306/ChamadoSENAC";
    static String username ="chamado";
    static String password ="root";
    Connection conexao = null;
    Connection con = conexao;
    Statement st = null;
    ResultSet result = null;
    
    private static conexao_bd cbd = new conexao_bd();
    DefaultListModel model;
    int Enter = 0;
    String [] Codig;

    /**
     * Creates new form JClienteExistente
     */
    public JClienteExistente() {
        initComponents();
    }
     private void conectar(){
         try{
            conexao = DriverManager.getConnection(url,username,password);
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro C025","ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void desconectar(){
        try {
            st.close();
            conexao.close();
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro C033","ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void Pesquisa() {
        initComponents();
        conectar();
        MostraPesquisa();
        list_pesquisa.setVisible(false);
        model= new DefaultListModel();
        list_pesquisa.setModel(model);

    }
    
    
    private void  Busca () {
        model = new DefaultListModel();
        int i=0; 
        String[] Codig = new String[4];
        String InstrucaoSQL="SELECT nome, cpf FROM `clientes` WHERE nome =  "+text_nomepesquisa;
        executaSQL(InstrucaoSQL);
        model.removeAllElements();
        conectar();
        try{  
            st = conexao.createStatement();
            result = st.executeQuery(InstrucaoSQL);     
            while (result.next()) {
                for (; i < 4;){
                model.addElement(result.getString("Nome"));
                Codig[i] = result.getString("CPF");
                i++;
                }
              }
            ResultadoPesquisa();
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "ERRO:C78 JCE", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        desconectar();
   }
     
   private void executaSQL(String sql) {
        try {
            st = conexao.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, result.CONCUR_READ_ONLY);
            st = conexao.createStatement();
            result = st.executeQuery(sql);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Nao foi possível executar o comando sql");
        }
    }
   
   private void ResultadoPesquisa() {
   
          try {
            result.first();
            text_nomeresult.setText(result.getString("Nome"));
            text_cpfresult.setText(result.getString("CPF"));
            text_cnpjresult.setText(result.getString("CNPJ"));
           
        } catch (Exception e) {
             e.printStackTrace();
            JOptionPane.showMessageDialog(null, "ERRO:C32 JCE", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
   
    }
   private void MostraPesquisa() {
        int Linha = list_pesquisa.getSelectedIndex();
        if (Linha >= 0) {
            String InstrucaoSQL="SELECT nome FROM clientes  where cpf= "+Codig[Linha]+" ";
            try {
                st = conexao.createStatement();
                result = st.executeQuery(InstrucaoSQL);
                 ResultadoPesquisa();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,"erro tusabe onde");
            }
          
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        label_fundo = new javax.swing.JLabel();
        text_nomepesquisa = new javax.swing.JTextField();
        list_pesquisa = new javax.swing.JList<>();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        label_nomeresult = new javax.swing.JLabel();
        text_nomeresult = new javax.swing.JTextField();
        label_cpfresult = new javax.swing.JLabel();
        text_cpfresult = new javax.swing.JTextField();
        label_cnpjresult = new javax.swing.JLabel();
        text_cnpjresult = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 51, 51));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clientes Existentes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLayeredPane2.setBackground(new java.awt.Color(51, 51, 51));

        label_fundo.setBackground(new java.awt.Color(51, 51, 51));
        label_fundo.setForeground(new java.awt.Color(51, 51, 51));
        jLayeredPane2.add(label_fundo);
        label_fundo.setBounds(-13, -10, 440, 270);

        text_nomepesquisa.setBackground(new java.awt.Color(255, 255, 255));
        text_nomepesquisa.setForeground(new java.awt.Color(51, 51, 51));
        text_nomepesquisa.setText("pesquisa");
        text_nomepesquisa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        text_nomepesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nomepesquisaActionPerformed(evt);
            }
        });
        text_nomepesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_nomepesquisaKeyReleased(evt);
            }
        });
        jLayeredPane2.add(text_nomepesquisa);
        text_nomepesquisa.setBounds(70, 0, 260, 20);

        list_pesquisa.setBackground(new java.awt.Color(255, 255, 255));
        list_pesquisa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        list_pesquisa.setForeground(new java.awt.Color(0, 0, 0));
        list_pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                list_pesquisaMousePressed(evt);
            }
        });
        jLayeredPane2.add(list_pesquisa);
        list_pesquisa.setBounds(70, 20, 260, 60);

        jLayeredPane1.setBackground(new java.awt.Color(51, 51, 51));
        jLayeredPane1.setForeground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        label_nomeresult.setForeground(new java.awt.Color(255, 255, 255));
        label_nomeresult.setText("Nome:");

        text_nomeresult.setBackground(new java.awt.Color(255, 255, 255));
        text_nomeresult.setForeground(new java.awt.Color(0, 0, 0));

        label_cpfresult.setForeground(new java.awt.Color(255, 255, 255));
        label_cpfresult.setText("CPF:");

        text_cpfresult.setBackground(new java.awt.Color(255, 255, 255));
        text_cpfresult.setForeground(new java.awt.Color(51, 51, 51));

        label_cnpjresult.setForeground(new java.awt.Color(255, 255, 255));
        label_cnpjresult.setText("CNPJ:");

        text_cnpjresult.setBackground(new java.awt.Color(255, 255, 255));
        text_cnpjresult.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_nomeresult, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(label_cpfresult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_cnpjresult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_nomeresult, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_cnpjresult, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_cpfresult, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nomeresult)
                    .addComponent(text_nomeresult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cpfresult)
                    .addComponent(text_cpfresult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cnpjresult)
                    .addComponent(text_cnpjresult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel1);
        jPanel1.setBounds(0, 0, 418, 130);

        jLayeredPane2.add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 100, 418, 140);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
      
    }//GEN-LAST:event_formInternalFrameOpened

    private void list_pesquisaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_pesquisaMousePressed
       MostraPesquisa();
        list_pesquisa.setVisible(false);
    }//GEN-LAST:event_list_pesquisaMousePressed

    private void text_nomepesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_nomepesquisaKeyReleased
         if(Enter == 0){
             Busca();
         }else{
            Enter = 0;
         }
    }//GEN-LAST:event_text_nomepesquisaKeyReleased

    private void text_nomepesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nomepesquisaActionPerformed
    list_pesquisa.setVisible(false);
    Enter = 1;    }//GEN-LAST:event_text_nomepesquisaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_cnpjresult;
    private javax.swing.JLabel label_cpfresult;
    private javax.swing.JLabel label_fundo;
    private javax.swing.JLabel label_nomeresult;
    private javax.swing.JList<String> list_pesquisa;
    private javax.swing.JTextField text_cnpjresult;
    private javax.swing.JTextField text_cpfresult;
    private javax.swing.JTextField text_nomepesquisa;
    private javax.swing.JTextField text_nomeresult;
    // End of variables declaration//GEN-END:variables
}
